#ifndef EX4_DEPENDENCIES_H
#define EX4_DEPENDENCIES_H

#include "Mtmchkin.h"
#include "utilities.h"
#include "Cards/Fairy.h"
#include "Cards/Barfight.h"
#include "Cards/Treasure.h"
#include "Cards/Merchant.h"
#include "Cards/Pitfall.h"
#include "Cards/Treasure.h"
#include "Cards/Vampire.h"
#include "Cards/Goblin.h"
#include "Cards/Dragon.h"
#include "Cards/Gang.h"
#include "Cards/CardUtilities.h"
#include "Players/Fighter.h"
#include "Players/Rogue.h"
#include "Players/Wizard.h"
#include "Players/PlayerUtilities.h"
#include <algorithm>
#include <string>
#include <fstream>
#include <deque>
#include <queue>
#include <map>
#include <vector>
#include <memory>

using std::string;
using std::ifstream;
using std::ofstream;
using std::cerr;
using std::endl;
using std::set;
using std::queue;
using std::vector;
using std::unique_ptr;
using std::map;
using std::cin;
using std::stoi;
using std::move;
using std::fill;
using std::count;

#endif //EX4_DEPENDENCIES_H
